.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml, manifests/deployment-dev.yml, manifests/deployment.yml, manifests/kustomization.yml, pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/EventGridEvent.java
This PR proposes to add an event hub consumer to read Blob Storage events. The consumer is based on Spring Cloud Stream and relies on Event Grid to receive events from blob storage to the dedicated event hub.
- Configuration of Event Hub integration using Kafka Protocol in the application properties file
- New basic consumer
- Review of deploy pipeline to support customization of manifests for different environment
- Review of code review pipeline to remove some exclusions
=> [CEN-1360] Add ehub consumer and review deploy strategy

pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/configuration/ThreadSafeHttpClient.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/event/EventHandler.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/BlobApplicationAware.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnector.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/Decrypter.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/IBlobRestConnector.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnectorTest.java, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/DecrypterTest.java, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/HttpClientTest.java
This PR enabled the 'TrustSelfSignedStrategy' in the creation of the HTTP client in order to allow the service to communicate with the *internal* APIM endpoint.
=> [CEN-1434] Create HTTP client with TrustSelfSignedStrategy

.github/CODEOWNERS
This PR proposes to add Alberto Re to the repository code owners.
- add alberto-re-pagopa to code owners
- avoid being dependent on a single person for PR approval
=> [CEN-1499] Add alberto-re-pagopa to code owners

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitter.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterTest.java, src/test/resources/application-nokafka.yml
With this PR we allow the splitting of the decrypted files into N files (chunks) of statically determined maximum size, where their size is expressed in lines.
The line threshold must be defined at the environment level, with a reasonable default.
- Add split service.
The split of decrypted blobs helps in case of big blob inputs.
The chunks grant horizontal scalability.
=> [CEN-1504] Implement decrypted blob splitting implementation.

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterTest.java
In case of successful split, currently, no message is logged.
With this PR we want to obtain information on the amount of chunks generated by a single blob after the split.
- Add a flag for successful split.
- Add log information about the number of chunks and the source blob.
- Add and enforced tests.
This PR further improve the logging ability of the decrypter in all the steps of its handler.
=> [CEN-1524] Impove log on successful split

.github/CODEOWNERS
This PR proposes to add Tommaso Lencioni to the repository code owners.
=> [CEN-1532] Add Tommaso Lencioni to code owners.

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/BlobApplicationAware.java, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/BlobApplicationAwareTest.java, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnectorTest.java
This PR improves the deletion of the local files, including the case of split.
The files are no longer deleted taking the blob name and its ".decrypt" counterpart.
Instead, every file inside the temporary directory whose name starts with the blob's name is deleted (this includes decrypted blob and chunks of it).
- Modified the blob deletion mechanic. Now it scans the name of the blobs and deletes every file in temporary folder that starts with it.
- Improved tests, given this change.
The introduction of the blob split wasn't backed up by a proper local deletion of the chunks.
Once established a convention for chunk's naming (original_blob_name+#current_blobs) is easy to remove just the desired files.
=> [CEN-1555] Improve local delete mechanic to include chunks

src/main/resources/application.yml, src/test/resources/application-nokafka.yml
This PR propose a way to define the line splitting threshold through an environment variable, instead of hard coding it.
- Set an environment variable name and default value for line splitting threshold in application properties.
This change allows us to specify a common threshold for all development environments.
Through k8 pod setting we can further customize this value for testing purposes.
=> [CEN-1592] Split threshold as environment variable

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnectorImpl.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java
This PR fix a naming convention discrepancy rose with the introduction of the splitting step.
The local files' name wasn't consistent between steps, leading to errors.
- Local chunk naming.
- Changed expected local files' name in Put step.
During e2e test an error is thrown while looking for local files.
With naming consistency the problem should be solved.
=> [CEN-1593] Fix chunk naming convention

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/BlobApplicationAware.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java
This PR propose a fix to the unwanted behaviour that resulted in the deletion of the blob chunks and not the original blob. 
- During the cleanup step the name of the original blob is obtained and every file whose name that starts with it is locally deleted.
This bug would lead to a clog of the decrypter instance.
=> [CEN-1594] Delete original blob

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnectorImpl.java, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnectorTest.java
This PR propose an improvement to logging during the download and upload step of a blob.
- Add log in case of successful get.
- Add log in case of successful put.
- Refactor log in case of failed get.
- Refactor log in case of failed put.
- Add new tests.
This change allows a better blob handling step reconstruction.
=> [CEN-1578] Improve blob GET and PUT logs

.github/CODEOWNERS
This PR propose to remove Alberto Re and add Andrea Morabito to code owners.
- modified code owners file to add Andrea Morabito as code owner.
Every developer of CSTAR team has to be code owner.
=> [CSMP-2] add Andrea Morabito to code owners.

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/DecrypterImpl.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/utils/LargeFileUtils.java
=> [RTD-264] Fix overflow copy for files greater than 2GB

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/AdeTransactionsAggregate.java
This PR proposes to fix a bug in the `posType` field validation.
- Changed validation pattern
The batch service may produces dirty `posType` with the value `99` and the decrypter must accepts it.
=> [RTD-424] bugfix on posType validation

manifests/deployment.yml, pom.xml
This PR proposes to promote the branch 'dev' into branch 'uat'.
- Vertically scaled resources
The micro service decrypter needs more resources for its execution.
=> Promotion to UAT

manifests/deployment.yml, pom.xml
This PR proposes to align the branch 'uat' with the branch 'main'.
The micro service decrypter must be released to the prod environment.
=> Promotion to main

manifests/deployment.yml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java
This PR proposed to fix naming convention problems on RTD flow.
- fix chunks naming convention for RTD flow
- fix the number of replicas to 4
This change is needed to avoid throwing IO exception during RTD chunks upload.
=> [TAE-176] Fix RTD naming convention

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/RtdTransaction.java
This PR proposes to add the model of a transaction ingested by RTD.
- add RTD transaction model
Decrypted files need to be validated. To do so for RTD transactions their DTO must be available.
=> [RTD-459] Add RTD transaction model

manifests/deployment.yml
This PR proposes to decrease replicas number to 2.
Given the significant speed up of memory validation we no longer need to parallelize the processing.
Thus 4 replicas take too much resources.
=> [RTD-719] Decrease replicas

Dockerfile, pom.xml
This PR proposes to enable Application Insights agent.
=> [RTD-747] Enable AppInsights agent

manifests/deployment.yml
This PR proposes to restore 2 replicas in deployment manifest.
- set 0 replicas in manifest
With this change we restore 2 desired replicas from hard coded 0 replicas after naming convention change.
=> [RTD-823] Set two replicas

Dockerfile, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnectorImpl.java
This PR proposes to add `If-None-Match` header to internal PUT request.
- add header.
We experienced duplicate events with the same payload. This caused multiple file processing.
With this change we prevent decrypted blob override.
=> [RTD-1165] Fix duplicate blob put

manifests/deployment.yml
=> Promote to UAT

.devops/cstar-rtd-code-review-pipelines.yml, .devops/cstar-rtd-deploy-pipelines.yml, .devops/deploy-pipelines.yml
This PR adds new aks pipelines. Also delete the old one code-review pipeline
=> chore: [RTD-1088] New pipelines

Dockerfile, src/main/resources/application.yml
This PR proposes to bump Application Insights agent version.
Also WARN logging level is set for kafka.
=> chore: [RTD-1219] Bump Application Insights agent version

.github/workflows/pr-title.yml, .github/workflows/release.yml, .releaserc.json
This PR proposes to add semantic versioning GitHub action.
- add GitHub action code.
=> chore: [RTD-816] Add semantic versioning GitHub action

.devops/cstar-rtd-code-review-pipelines.yml
=> chore: code review pipeline

.devops/cstar-rtd-deploy-pipelines.yml
=> fix: [RTD-1468] fix bug and change var name

.github/workflows/release.yml
=> chore: [RTD-1526] update checkout version

pom.xml
=> fix: [RTD-1574] upgrade version

.devops/cstar-rtd-deploy-pipelines.yml, .github/CODEOWNERS, helm/rtd/Chart.yaml, helm/rtd/values.yaml
this PR proposes to include the `helm` directory among those that trigger a deploy.
- include helm directory in pipeline deploy
- bump chart version to 3.0.0
=> chore: [RTD-1564] deploy on helm changes

.github/workflows/anchore.yml, helm/rtd/Chart.lock, helm/rtd/Chart.yaml
This PR proposes to downgrade the helm chart version to 2.8.0
=> chore: [RTD-1564] fix helm chart version to v2.8.0

.devops/cstar-rtd-deploy-pipelines.yml, .github/CODEOWNERS, .github/workflows/anchore.yml, helm/rtd/Chart.yaml, helm/rtd/values.yaml
* [RTD-1564] add helm among paths that trigger deploy
* [RTD-1564] upgrade helm chart to 2.8.0
* [RTD-1564] Dockerfile now triggers the deploy pipeline
* [RTD-1564] add lucaconsalvi to CODEOWNERS
[RTD-1564]: https://pagopa.atlassian.net/browse/RTD-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1564]: https://pagopa.atlassian.net/browse/RTD-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1564]: https://pagopa.atlassian.net/browse/RTD-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1564]: https://pagopa.atlassian.net/browse/RTD-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Promotion to UAT

.github/workflows/anchore.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml, Dockerfile, pom.xml
This PR pins the sha of github actions used by workflows and the sha of base docker image used to build microservice images.
- anchore.yml now uses pinned actions
- release.yml now uses pinned actions
- pr-title.yml now uses pinned actions
- base build and runtime image of Dockerfile
=> fix: [RTD-1736] pin docker and github action verison

.github/workflows/anchore.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml, Dockerfile, pom.xml
* [RTD-1736] pin docker and github action verison
* [RTD-1736] pin app version
* [RTD-1736] update docker image
[RTD-1736]: https://pagopa.atlassian.net/browse/RTD-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1736]: https://pagopa.atlassian.net/browse/RTD-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1736]: https://pagopa.atlassian.net/browse/RTD-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Promote to UAT

.github/workflows/anchore.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml, Dockerfile, pom.xml
* [RTD-1736] pin docker and github action verison
* [RTD-1736] pin app version
* [RTD-1736] update docker image
[RTD-1736]: https://pagopa.atlassian.net/browse/RTD-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1736]: https://pagopa.atlassian.net/browse/RTD-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1736]: https://pagopa.atlassian.net/browse/RTD-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Promote in PROD

.github/workflows/release.yml
=> fix: [RTD-1775] fix pinning release

.github/workflows/release.yml
Reverts pagopa/rtd-ms-decrypter#108
=> chore: Revert "fix: [RTD-1775] fix pinning release"

.github/workflows/anchore.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml, Dockerfile, pom.xml
=> chore: Promote to UAT

Dockerfile, helm/rtd/values.yaml, pom.xml
This PR's purpose is about to run the container as no root user, updating  maven from 3.9.0 to 3.9.3 and updating ApplicationInsights-Java from 3.4.11 to 3.4.14
- Run the container as no root user
- Update  maven from 3.9.0 to 3.9.3
- Update ApplicationInsights-Java from 3.4.11 to 3.4.14
- Bump version
- Update spring-boot-starter-parent from 3.0.5 to 3.1.1
- Update spring-cloud from 2022.0.2 to 2022.0.3
=> chore: [RTD-1807] run as no root

.github/workflows/release.yml, Dockerfile, helm/rtd/values.yaml, pom.xml
This PR's purpose is about to run the container as no root user, updating  maven from 3.9.0 to 3.9.3 and updating ApplicationInsights-Java from 3.4.11 to 3.4.14
- Run the container as no root user
- Update  maven from 3.9.0 to 3.9.3
- Update ApplicationInsights-Java from 3.4.11 to 3.4.14
- Bump version
- Update spring-boot-starter-parent from 3.0.5 to 3.1.1
- Update spring-cloud from 2022.0.2 to 2022.0.3
=> chore: Promote to PROD

helm/rtd/values-prod.yaml, helm/rtd/values.yaml
This PR allow the microservice to connect to new rtd-platform-events queue in DEV and UAT while keeping PROD to old evh-ns
=> chore: [RTD-1895] Update helm chart to use new evh

helm/rtd/values-prod.yaml, helm/rtd/values.yaml
=> chore: update helm chart to use new evh (#118)

Dockerfile, helm/rtd/values.yaml, pom.xml
This PR proposes to update spring boot and its dependencies
package | old version | new version
-- | -- | --
org.springframework.boot| 3.1.1 | 3.1.2
snakeyaml | 2.0 | 2.1
run image | amazoncorretto:17.0.7-alpine3.17 | amazoncorretto:17.0.8-alpine3.18
appinsights | 3.4.11 | 3.4.15
org.bouncycastle| 1.72.2 | 1.76
commons-io | 2.11.0 | 2.13.0 
com.opencsv | 5.7.1 | 5.8
maven-checkstyle-plugin | 3.1.2 | 3.3.0
checkstyle | 10.0 | 10.12.2
spring-cloud | 2022.0.3 | 2022.0.4
=> chore: [RTD-1875] update docker file and dependencies

pom.xml
package | old version | new version
-- | -- | --
spring boot | 3.1.2 | 3.1.3
=> chore: [RTD-1875] update kafka dependecies

helm/rtd/values-prod.yaml
This PR enable decrypter to use new platform-events queue from PROD env
- remove of overridden prod properties to use the default ones
=> chore: [RTD-1904] Update helm prod to use new platform-events evh

helm/rtd/values-prod.yaml
=> chore: update helm prod to use new platform-events evh (#125)

helm/rtd/values-prod.yaml, pom.xml
=> chore: deploy to Prod

.github/workflows/anchore.yml, helm/rtd/values-prod.yaml
=> Promote to PROD

helm/rtd/values-dev.yaml
This PR proposes to decrease CPU requests in DEV environment.
- decrease CPU request and limit in DEV value
With this change we can spare computing node in DEV environment.
=> chore: [RTD-2092] reduce CPU requests and limits in DEV

.github/workflows/scan.yml, Dockerfile, pom.xml
This PR proposes to update the snappy java version to fix cve.
Atm it is not possible to bump the kafka dependency to 3.6.0 since it is not compatible with the actual test codebase. In particular there is some incompatibility between the spring-kafka-test (spring package) and kafka-clients (apache package). We do not proceed to do any refactor and wait until spring boot brings in the 3.6.0 version.
- replace grype with trivy
- update dependency of snappy java
=> fix: [RTD-2134] update snappy java to solve cve

.github/workflows/scan.yml, Dockerfile, pom.xml
=> fix: promotion to uat - update snappy java

.github/CODEOWNERS
Description
This PR use team as codeowner
List of Changes
updated file
Motivation and Context
[Operational Excellence Task](https://pagopa.atlassian.net/browse/OE-143)
=> docs: CODEOWNERS

pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/DecrypterImpl.java
This PR proposes to add a new exception to the catch clause during decryption.
- add `ClassCastException` to catch
- fix code smells.
During UAT integration of an acquirer we received a malformed PGP file that led to micro-service failure during decryption. We noticed that `ClassCastException` was not caught.
=> fix: [RTD-2279] Catch cast exeption

Dockerfile, pom.xml
=> fix: promotion to UAT - fix cve

helm/rtd/values-dev.yaml, helm/rtd/values-uat.yaml
This PR proposes to enable the `forceRedeploy` flag in the helm deployment configuration. The pod rollout will happen automatically now and there is no needed of manual deployment restart to spin up the new pods.
=> chore: [RTD-2301] enable force redeploy flag

helm/rtd/values-dev.yaml, helm/rtd/values-uat.yaml
=> chore: promotion to UAT - enable forceRedeploy

pom.xml
Update dependencies
| Dependecy | Previews version | Updated version | 
| --- | --- | --- |
| `spring boot` | `3.1.5` | `3.2.1` |
| `spring-cloud` | `2022.0.4` | `2023.0.0` |
| `bcpg-jdk18on` | `1.76` | `1.77` |
| `commons-io` | `2.13.0` | `1.15.1` |
| `commons-text` | `1.10.0` | `1.11.0` |
| `maven-checkstyle-plugin` | `3.3.0` | `3.3.1` |
| `checkstyle ` | `10.12.2` | `10.12.7` |
| `kafka ` | `3.5.1` | `3.6.1` |
=> chore: [RTD-2307] bumb spring boot version

.github/workflows/scan.yml
=> chore: fix cve scan when no cve found (#154)

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/DecrypterImpl.java
This PR proposes to catch all decryption exceptions.
- catch Exception in decrypt routine
With this change we avoid losing uncaught decryption errors.
=> fix: [RTD-2387] Catch all decryption exceptions

pom.xml
=> chore: [RTD-2387] Bump pom version

helm/rtd/values-prod.yaml
This PR propose to set an affinity and anti-affinity policy in production environment.
- change helm.
With this change we can allocate the 2 replicas in different nodes.
=> chore: [RTD-2444] add pod affinity for prod environment

helm/rtd/values.yaml
=> chore: [RTD-2501] update liveness and readiness initial delay seconds

pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/telemetry/AppInsightConfig.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/telemetry/SpringCloudKafkaBinderInstrumentation.java, src/main/resources/application.yml
- update OTEL and exporter
- disable metric collection
=> chore: [RTD-2480] bump OTEL and exporter version

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/WalletExportHeader.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java, src/test/resources/PAGOPAPM_NPG_CONTRACTS_20240323000000_001_OUT.decrypted
The header model was misaligned.
- update export header model
- add validation
=> fix: [CHK-2919] Fix header fields

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobVerifierImpl.java, src/test/resources/PAGOPAPM_NPG_CONTRACTS_20240323000000_001_OUT.decrypted
=> fix: [CHK-2922] Remove contract CREATE KO check

pom.xml
=> chore: restore 1.2.1 version on pom.xml

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/event/EventHandler.java
This PR proposes to fix the deserialization of the payload of kafka messages
=> fix: EventGridEvent deserialization

pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/config/BouncyCastleFeature.java
=> fix: revert bouncy castle update

pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/config/BouncyCastleFeature.java
=> fix: promotion to uat - fix bouncy castle native

.devops/cstar-rtd-deploy-pipelines.yml
=> fix: disable native image by default

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/model/BlobApplicationAware.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java
Solve these 2 tasks:
https://pagopa.atlassian.net/browse/RTD-2591
https://pagopa.atlassian.net/browse/RTD-2581
=> chore: [RTD-2582] change log level

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java
This PR proposes to change log formato to place `[Wallet]` before messages related to wallet migration files.
=> chore: [TAE-220] add wallet tag on wallet logs

.github/workflows/scan.yml, pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/DecrypterImpl.java
=> chore: [RTD-292] fix cve and github action

src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterImpl.java, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobSplitterTest.java, src/test/resources/PAGOPAPM_NPG_CONTRACTS_20240301000000_002_OUT.decrypted, src/test/resources/PAGOPAPM_NPG_CONTRACTS_20240318000000_001_OUT.decrypted, src/test/resources/PAGOPAPM_NPG_CONTRACTS_20240319000000_001_OUT.decrypted, src/test/resources/PAGOPAPM_NPG_CONTRACTS_20240320000000_001_OUT.decrypted
This PR proposes to fix an uncaught exception in case of malformed checksum.
- handle malformed checksum by logging and fail
- fix some manutenability issues
With this change we avoid breaking file processing if a file checksum is malformed.
=> fix: [TAE-304] Handle malformed checksum

.github/workflows/release.yml, .github/workflows/scan.yml, pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/telemetry/AppInsightConfig.java
- upgrade spring boot to 3.3.4
- upgrade opentelemetry to 1.43.0
- upgrade opentelementry-instrumentation to 2.9.0 (target SDK 1.43.0)
- upgrade azure exporter to 1.0.0-beta.30 (target SDK 1.43.0)
- upgrade github actions
=> fix: [TAE-336] Fix CVE

.github/workflows/release.yml, .github/workflows/scan.yml, pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/telemetry/AppInsightConfig.java
=> fix: [TAE-336] Fix CVE (#218)

.github/workflows/scan.yml
Updating to the latest version (v0.29.0) of trivyaction by pinning the hash.
- on scan.yml file update version
The new version of trivyaction fixes a too many requests issue that currently leads to the failure to produce the vulnerability report
=> chore: [TAE-353] Update version Trivy action

.devops/cstar-rtd-deploy-pipelines.yml, pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/RtdMsDecrypterApplication.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobVerifierImpl.java, src/main/resources/META-INF/native-image/reflect-config.json, src/main/resources/META-INF/native-image/resource-config.json, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/RtdMsDecrypterApplicationTest.java
=> fix: [TAE-198] enable native build configuration (#225)

.devops/cstar-rtd-deploy-pipelines.yml, .github/workflows/scan.yml, pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/RtdMsDecrypterApplication.java, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobVerifierImpl.java, src/main/resources/META-INF/native-image/reflect-config.json, src/main/resources/META-INF/native-image/resource-config.json, src/test/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/RtdMsDecrypterApplicationTest.java
=> fix: Promote native build to prod

pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnectorImpl.java
Update version of spring-starter-web for fix CVE 
- modify version of pom.xml 
Fix CVE: [CVE-2024-50379](https://avd.aquasec.com/nvd/cve-2024-50379)
=> fix: [TAE 352] update version of spring-starter-web to fix CVE

pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/service/BlobRestConnectorImpl.java
=> fix: [TAE 352] Promotion UAT 

pom.xml
Upgrade springboot-starter-parent to include the updated springboot-starter-tomcat dependency, which resolves the vulnerability in tomcat-embed-core.
To resolve the critical CVE in springboot-starter-tomcat, an upgrade to springboot-starter-parent 3.4.3 is required.
[CVE-2025-24813](https://avd.aquasec.com/nvd/cve-2025-24813)
=> fix: TAE-364 upgrade springboot starter tomcat

pom.xml, src/main/java/it/gov/pagopa/rtd/ms/rtdmsdecrypter/telemetry/AppInsightConfig.java
=> fix: [TAE-364] Promotion UAT
